### ISSUE TITLE
Disabled is ignored if NODE_ENV=production

### ISSUE THREAD

**Issue by Stanko** [raunofreiberg/inspx#8]
Hello and thank you for the great library.

I have a specific problem, as I would like inspx to stay active on development/qa/preview deploys. This would help people who review and test features on these non-production branches.

But it seems that library itself disables when `NODE_ENV` is set to `production` and `disabled` is ignored.

Code looks something like this:

```js
const isPreviewOrDev =
  process.env.NODE_ENV === 'development' || process.env.PREVIEW_ENV;

<Inspect disabled={!isPreviewOrDev}>
  <Component {...props} {...pageProps} />
</Inspect>
```

Where `PREVIEW_ENV` is a env variable which tells the app it runs in a (p)review mode and not in a real production mode.

I hope I was clear enough 🙈 

Thank you!

**Comment by brunooomelo** [comment]
your condition is a problem, if PREVIEW_ENV have a something your condition is true.

**Comment by Stanko** [comment]
The condition is good, if `PREVIEW_ENV` is set (to "1" for example) that detects if the current env is preview (and the first part detects local development), and any of these two scenarios scenario, `inspx` is enabled.

The problem lies here I think:
https://unpkg.com/inspx@0.0.1-alpha.6/dist/index.js

**Comment by brunooomelo** [comment]
![image](https://user-images.githubusercontent.com/12174318/126511191-b5e25cc2-0efd-4aea-a3f0-742b304687f3.png)
I think your problem is  your condition

its correct
![image](https://user-images.githubusercontent.com/12174318/126511538-6e33b598-0dcb-4e6d-887c-6bfab3c12022.png)

it's wrong
![image](https://user-images.githubusercontent.com/12174318/126511622-502a92a1-f16d-4ddc-89b8-67ea107caa9a.png)

it's work
![image](https://user-images.githubusercontent.com/12174318/126512150-0bd2f023-e655-4e0f-84f2-9e282e4f2008.png)

![image](https://user-images.githubusercontent.com/12174318/126512602-d5815b42-1d11-4c35-b9e8-6c1c27ee9c10.png)

**Comment by Stanko** [comment]
Everything coming from ENV is a string. Meaning that it can be `'0'` `'1'` `'true'` or `'anything else'` and it will work and correctly detect preview env. Like you've shown in the second example:

<img src="https://user-images.githubusercontent.com/12174318/126511622-502a92a1-f16d-4ddc-89b8-67ea107caa9a.png" />

When this is `true`, like in the example above, the code I wrote should work, as I have negation `!` in front of it, meaning that disabled should be `false`.

```js
<Inspect disabled={!isPreviewOrDev}>
```

If the ENV var is empty (not defined in the terminal), then it will be "falsy" and disabled will be `true`

**Comment by Stanko** [comment]
I see where from the confusion came from.

We are passing string "1" when `PREVIEW_ENV` needs to be true, and not setting the ENV variable at all in production.

**Comment by brunooomelo** [comment]
> I see where from the confusion came from.
> 
> We are passing string "1" when `PREVIEW_ENV` needs to be true, and not setting the ENV variable at all in production.

what's the result? 

for me: 
![image](https://user-images.githubusercontent.com/12174318/126515840-0472aa10-335b-4688-bb39-d84087c620c3.png)

**Comment by Stanko** [comment]
Correct, which means disabled is set to false, and imgix should work - but it doesn’t.

**Comment by brunooomelo** [comment]
what's the version? because I tried and it's worked.

**Comment by brunooomelo** [comment]
its NEXTJS?

**Comment by Stanko** [comment]
Indeed it is.

**Comment by brunooomelo** [comment]
I have the same problem when  I will build my project in server side the envs is correct but in client-server, the envs is wrong.

**Comment by brunooomelo** [comment]
I resolved with client-side env 

[Documentation](https://nextjs.org/docs/basic-features/environment-variables)

look this [PR](https://github.com/brunooomelo/personal-site/pull/12) the implementation
